-- NHIC MCI Surveillance — Postgres (Neon) schema. Idempotent: safe to run on every job start.
--
-- Dates are ISO-8601 TEXT (not DATE/TIMESTAMPTZ) on purpose: scraped sources give
-- partial or missing dates, and the NLP layer normalises to "YYYY-MM-DD[THH:MM:SS]"
-- strings. Analytics read the derived `occurred_at` column on the view below.

CREATE TABLE IF NOT EXISTS incidents (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id       TEXT NOT NULL UNIQUE,
    semantic_id     TEXT,
    title           TEXT NOT NULL,
    description     TEXT,
    full_text       TEXT,
    source_name     TEXT,
    source_url      TEXT,
    source_tier     SMALLINT NOT NULL DEFAULT 3,
    media_type      TEXT,
    location        TEXT,
    district        TEXT,
    province        TEXT,
    latitude        DOUBLE PRECISION,
    longitude       DOUBLE PRECISION,
    severity        SMALLINT NOT NULL DEFAULT 1,
    deaths          INTEGER NOT NULL DEFAULT 0,
    injured         INTEGER NOT NULL DEFAULT 0,
    missing         INTEGER NOT NULL DEFAULT 0,
    incident_type   TEXT,
    status          TEXT DEFAULT 'active',
    detected_at     TEXT NOT NULL,
    published_at    TEXT,
    event_date      TEXT,
    ai_summary      TEXT,
    ai_confidence   REAL DEFAULT 0,
    is_historical   SMALLINT NOT NULL DEFAULT 0,
    verified        SMALLINT NOT NULL DEFAULT 0,
    -- NULL = not yet checked by Claude, 1 = confirmed Rwanda, 0 = rejected
    rwanda_verified SMALLINT
);

CREATE TABLE IF NOT EXISTS scrape_log (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source           TEXT,
    scrape_type      TEXT,
    started_at       TEXT,
    finished_at      TEXT,
    articles_seen    INTEGER NOT NULL DEFAULT 0,
    incidents_added  INTEGER NOT NULL DEFAULT 0,
    error            TEXT
);

CREATE TABLE IF NOT EXISTS scrape_cursor (
    source    TEXT PRIMARY KEY,
    last_url  TEXT,
    last_date TEXT,
    page      INTEGER NOT NULL DEFAULT 1
);

-- Dashboard accounts (email + password). Used by the Next.js app only.
CREATE TABLE IF NOT EXISTS users (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email          TEXT NOT NULL UNIQUE,          -- always stored lower-cased
    name           TEXT,
    password_hash  TEXT NOT NULL,                 -- scrypt$N$r$p$salt$hash
    failed_logins  INTEGER NOT NULL DEFAULT 0,
    locked_until   TIMESTAMPTZ,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Single-use password reset links. Only a SHA-256 of the emailed token is stored.
CREATE TABLE IF NOT EXISTS password_resets (
    token_hash  TEXT PRIMARY KEY,
    user_id     INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    expires_at  TIMESTAMPTZ NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_password_resets_user ON password_resets (user_id);

CREATE INDEX IF NOT EXISTS idx_incidents_event_date ON incidents (event_date);
CREATE INDEX IF NOT EXISTS idx_incidents_district   ON incidents (district);
CREATE INDEX IF NOT EXISTS idx_incidents_type       ON incidents (incident_type);
CREATE INDEX IF NOT EXISTS idx_incidents_detected   ON incidents (detected_at);
CREATE INDEX IF NOT EXISTS idx_incidents_deaths     ON incidents (deaths);
CREATE INDEX IF NOT EXISTS idx_incidents_semantic   ON incidents (semantic_id);

-- Everything the dashboard shows. Rows Claude rejected as non-Rwanda are hidden.
-- occurred_at = event date when known, otherwise when the article was detected.
CREATE OR REPLACE VIEW verified_incidents AS
    SELECT *, COALESCE(NULLIF(event_date, ''), detected_at) AS occurred_at
    FROM incidents
    WHERE rwanda_verified IS DISTINCT FROM 0;
